name: Scorecard analysis workflow
on: 
  push:
    branches: [main]
  pull_request:

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    
    steps:
      # TODO: if pull_request
      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Run analysis"
        #uses: docker://ossf/scorecard/analyze@sha256:xxx
        uses: docker://laurentsimon/scorecard-action:latest
        with:
          policy_file: .github/scorecard.yml
          sarif_file: results.sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      # https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      # Optional.
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      
      - name: "Upload SARIF results"
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
